"""init migrations

Revision ID: 273c92170998
Revises: a09019ae4cdc
Create Date: 2022-05-10 16:25:37.673437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "273c92170998"
down_revision = "a09019ae4cdc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("books", "title", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("bookshelves", "test")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bookshelves", sa.Column("test", sa.VARCHAR(), nullable=True))
    op.alter_column("books", "title", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
