"""book price status

Revision ID: a09019ae4cdc
Revises: 2a7778bcde76
Create Date: 2022-05-09 16:38:30.031626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a09019ae4cdc"
down_revision = "2a7778bcde76"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "books", sa.Column("price", sa.DECIMAL(precision=5, scale=2), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("books", "price")
    # ### end Alembic commands ###
