"""some message

Revision ID: b7437e092873
Revises: 
Create Date: 2022-05-08 20:26:53.541964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7437e092873'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookshelves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookshelves_id'), 'bookshelves', ['id'], unique=False)
    op.create_index(op.f('ix_bookshelves_number'), 'bookshelves', ['number'], unique=False)
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('bookshelve_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bookshelve_id'], ['bookshelves.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=False)
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.drop_index(op.f('ix_books_id'), table_name='books')
    op.drop_table('books')
    op.drop_index(op.f('ix_bookshelves_number'), table_name='bookshelves')
    op.drop_index(op.f('ix_bookshelves_id'), table_name='bookshelves')
    op.drop_table('bookshelves')
    # ### end Alembic commands ###
